name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
  pull_request:
jobs:
  github-actions:
    name: github-actions
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - run: npm ci
      - name: install node_module
        run: npm i
      - name: review dog
        uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'
      - name: Check Eslint
        run: npm run lint